### ISSUE TITLE
GhjCompilation problem

### ISSUE THREAD

**Issue by Clourid** [asuleymanov/sbdd#1]
$ go build sbdd.go
# github.com/asuleymanov/rpc/client
C:\Users\admi\go\src\github.com\asuleymanov\rpc\client\functions.go:69:79: undefined: PC_Vote
C:\Users\admi\go\src\github.com\asuleymanov\rpc\client\functions.go:69:91: undefined: PC_Options
C:\Users\admi\go\src\github.com\asuleymanov\rpc\client\functions.go:166:104: undefined: PC_Vote
C:\Users\admi\go\src\github.com\asuleymanov\rpc\client\functions.go:166:116: undefined: PC_Options

**Comment by asuleymanov** [comment]
Hello.
Please update the "github.com/asuleymanov/rpc" library by running the command
`` `
go get -u github.com/asuleymanov/rpc
`` `
This should help in solving this problem.

**Comment by Clourid** [comment]
problem is not solved, more errors
I have win7 32

$ go build sbdd.go
# github.com/asuleymanov/rpc/client
C:\Users\admi\go\src\github.com\asuleymanov\rpc\client\functions.go:69:79: undefined: PC_Vote
C:\Users\admi\go\src\github.com\asuleymanov\rpc\client\functions.go:69:91: undefined: PC_Options
C:\Users\admi\go\src\github.com\asuleymanov\rpc\client\functions.go:167:104: undefined: PC_Vote
C:\Users\admi\go\src\github.com\asuleymanov\rpc\client\functions.go:167:116: undefined: PC_Options
C:\Users\admi\go\src\github.com\asuleymanov\rpc\client\functions.go:403:63: undefined: ArrTransfer
C:\Users\admi\go\src\github.com\asuleymanov\rpc\client\functions.go:659:84: undefined: PC_Vote
C:\Users\admi\go\src\github.com\asuleymanov\rpc\client\functions.go:659:96: undefined: PC_Options

**Comment by asuleymanov** [comment]
Check the "C: \ Users \ admi \ go \ src \ github.com \ asuleymanov \ rpc \ client \" file for the file "client_type.go".
If it is not there then the library has not been updated.
In this situation, the best thing is simply to download the library as an archive using this link "https://github.com/asuleymanov/rpc/archive/master.zip".
And unzip the uploaded archive to the "C: \ Users \ admi \ go \ src \ github.com \ asuleymanov \ rpc \" site before cleaning this folder.

**Comment by asuleymanov** [comment]
Sorry, I misled you.
I forgot to update the library on the github server.
Try running the command now
`` `
go get -u github.com/asuleymanov/rpc
`` `

I apologize for the inconvenience.

**Comment by Clourid** [comment]
Thanks for the help
The compilation was successful!
Now, when
 invalid character is started, 'i' looking for beginning of value

**Comment by Clourid** [comment]
Recollected and earned
And unless with wss: //steemd.steemit.com will work,?

**Comment by Clourid** [comment]
Everything works, thank you

**Comment by asuleymanov** [comment]
If the system stops working with "wss: //steemd.steemit.com", which is likely to happen. I can offer two more fully working node addresses.
"wss: //seed.bitcoiner.te, wss: //rpc.steemliberator.com"
